First attempt at checkpoints
danbraunai/simple_stories_train pull request #11
Opened 2024-08-08 14:30 UTC by ThomasWMarshall

## Description
Adds checkpoint saving.

## How Has This Been Tested?
Running locally, verifying that the saved files contain the expected information.

2024-08-08 14:35 UTC, ThomasWMarshall commented
Both the ApolloResearch sample repo that this repo was forked from and the starter code found in `train_gpt2.py` contain functions for saving parameters. If we can, I suggest that we forgo the code in `train_gpt2.py` and standardize on the simpler method from the ApolloResearch repo which really boils down to `torch.save(model.state_dict(), model_file)`. This would simplify things by keeping them consistent between `train_llama.py` and `train_gpt2.py`.

2024-08-08 20:49 UTC, danbraunai requested changes
Thanks for this! Made some comments.

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/train_gpt2.py
> +from utils import save_model_and_config, print0, is_checkpoint_step
Best to use package name to import, i.e. simple_stories_train.utils. Doing so lets you run code from anywhere without issues.

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/train_gpt2.py
> +        os.makedirs(checkpoints_dir, exist_ok=True)
You can do something like `checkpoints_dir.mkdir(parents=True, exist_ok=True)` and not have to mix Pathlib with os.

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/utils.py
> +def is_checkpoint_step(step: int):
return type is a bool

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/train_gpt2.py
> +            # save checkpoint
Don't need comment here

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/train_gpt2.py
> +        if checkpoints_dir is not None and is_checkpoint_step(step + 1):
I think is_checkpoint_step should just take in `step` and not `step + 1`

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        os.makedirs(checkpoints_dir, exist_ok=True)
os -> Pathlib.mkdir

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/utils.py
> +def print0(*args: Any, **kwargs: Any):
nit: return type annotation (None)

2024-08-08 20:49 UTC, danbraunai commented on simple_stories_train/utils.py
> +    return (0 < step < 1000 and (step & (step - 1)) == 0) or step % 1000 == 0
bahaha I have never seen `(step & (step - 1)) == 0)` before. Ludicrous, but yeah it's nice. Though I would put a docstring here explaining what this actually does. Ideally I'd also add a simple test `test_checkpoint_step` which just runs this over some of the interesting values and gives you what you'd expect.

2024-08-08 20:51 UTC, danbraunai commented
>This would simplify things by keeping them consistent between train_llama.py and train_gpt2.py.

I'm not sure we care much about supporting gpt2 for now. But yeah as to your general point, the llmc code that this script was ~copied from has the property that nearly everything is in one file. This can be nice. But yeah for our purposes I don't think this is necessary so I'm fine with starting to split things up into new files (as you have done with your utils).

2024-08-11 03:54 UTC, ThomasWMarshall commented
Thanks for the review! I've done my best to address them all. Please don't hesitate to reopen any of them if you'd like me to revisit.

2024-08-11 07:24 UTC, danbraunai-apollo approved these changes
Looks great, cheers. I'll merge it.

2024-08-11 07:26 UTC, merged