Add Typing to Llama Training
danbraunai/simple_stories_train pull request #9
Opened 2024-08-05 18:05 UTC by lennart-finke

## Description
Added Jax and regular typing to `llama_train.py`

## Related Issue
Should close #4.

## How Has This Been Tested?
Executing the script in a Colab instance.

2024-08-05 18:29 UTC, lennart-finke commented
Alright, will have to work on this some more as the checks indicate.

2024-08-05 19:16 UTC, lennart-finke commented
Now it might go through. If someone has time, I recommend double checking the jaxtyping hints though, as I was not entirely sure everywhere.

2024-08-08 21:20 UTC, danbraunai requested changes
Thanks for this. Bunch of comments. Btw I think you may need to merge main into this branch

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        attention_mask: Int[torch.Tensor, "batch offset_pos"],
This will probably be Bool and not Int?

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        attention_mask: Int[torch.Tensor, "batch offset_pos"],
Probably nicer to do `from torch import Tensor` at the top and then make all of these a bit shorter.

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        attention_mask: None | Int[torch.Tensor, "batch offset_pos"] = None,
Nit: I think standard to have the None after the non-none stuff, as you have later

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    def __init__(self, hidden_size: int, eps=1e-6):
nit: type `eps` to float

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    def forward(self, x: torch.Tensor) -> torch.Tensor:
Probably best to type as `def forward(self, x: Float[Tensor, "... dim"]) -> Float[Tensor, "... dim"]`.

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
Can use `def forward(self, hidden_states: Float[Tensor, "... dim"]) -> Float[Tensor, "... dim"]`.

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    ) -> Float[torch.Tensor, "batch pos d_model"]:
You can actually type as 
```
    def forward(
        self, x: Float[torch.Tensor, "... pos d_model"]
    ) -> Float[torch.Tensor, "... pos d_model"]:
```
because this will work whether there is a batch dimension or not (or e.g. two batch dimensions). "..." stands for zero or more axes https://docs.kidger.site/jaxtyping/api/array/

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        self.LLMC_SKIP_INIT = 1  # don't init this one, we will tie weights
This change seems sus

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +                if not hasattr(self, "LLMC_RESIDUAL_SCALE_FLAG")
doesn't seem right. The self.apply will apply to every submodule.

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        targets: None | Float[torch.Tensor, "batch pos vocab"] = None,
nit: None after other type. And Float[torch.Tensor, "... pos vocab"]

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    ):
return annotation missing

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    ):
missing return type

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    ) -> Float[torch.Tensor, "batch pos"]:
probably works with "... pos"?

Nit: None before int.

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +def _peek_data_shard(filename: str):
missing return type

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +def _load_data_shard(filename: str):
missing return type

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +        self.current_shard = -1
How come this change was made?

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    t = tensor.detach().cpu().to(torch.float32)
I think we deleted all the below from main. I'm guessing you hadn't pulled that latest main onto your branch?

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    import time
best to import at top of file

2024-08-08 21:20 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    # do one forward pass to generate ground truth for our C tests
I think we deleted all this too

2024-08-09 13:13 UTC, lennart-finke commented on simple_stories_train/train_llama.py
> +        attention_mask: Int[torch.Tensor, "batch offset_pos"],
Maybe it should be Bool, yes. I got this from transformerlens (https://github.com/TransformerLensOrg/TransformerLens/blob/main/transformer_lens/components/abstract_attention.py), but did not understand why

2024-08-09 13:18 UTC, lennart-finke commented on simple_stories_train/train_llama.py
> +    t = tensor.detach().cpu().to(torch.float32)
Yes, looks like it.

2024-10-08 16:11 UTC, danbraunai approved these changes
Looks good!

2024-10-08 16:11 UTC, danbraunai commented on simple_stories_train/train_llama.py
> +    )  -> tuple[Float[Tensor, "batch pos"] | None, Tensor | None]:
-> `tuple[Float[Tensor, "batch pos"] | None, Float[Tensor, ""] | None]`

2024-10-10 16:17 UTC, merged